
initialInputDir = 'G:\ESEM Paper\ESEM simulationDatafiles\detailedStat_';
% labels = { ...
%     'Growth_0.5to2.5_1_' ...
%     ,'Growth_0.5to2.5_2_' ...
%     ,'Growth_0.5to2.5_3_' ...
%     ,'Growth_1to3_1_' ...
%     ,'Growth_1to3_2_' ...
%     ,'Growth_1to3_3_' ...
%     ,'Growth_1to3_4_' ...
%     ,'Growth_1to3_5_' ...
%     ,'Growth_1to3_6_' ...
%     ,'Growth_1.5to3.5_1_' ...
%     ,'Growth_1.5to3.5_2_' ...
%     ,'Growth_1.5to3.5_3_' ...
%     ,'Growth_2to4_1_' ...
%     ,'Growth_2to4_2_' ...
%     ,'Growth_2to4_3_' ...
%     ,'Growth_2to4_4_' ...
%     ,'Growth_2to4_5_' ...
%     ,'Growth_2to4_6_' ...
%     ,'Growth_2to4_7_' ...
%     ,'Growth_2to4_8_' ...
%     ,'Growth_2to4_9_' ...
%     ,'Growth_3to5_1_' ...
%     ,'Growth_3to5_2_' ...
%     ,'Growth_3to5_3_' ...
%     ,'Growth_3to5_4_' ...
%     ,'Growth_4to6_1_' ...
%     ,'Growth_5to7_1_' ...
%     }';

for i = length(labels):-1:1
    
    inputFileLocation = [initialInputDir labels{i}];
    t = 1;
    
    while(exist([inputFileLocation num2str(t, '%05d') '.txt'],'file'))
        
        clear data
        inputDir = [inputFileLocation num2str(t, '%05d') '.txt'];
        data = importdata(inputDir);
        
        if isempty(data)
            break
        end
        
        temp = length(strfind(strjoin(data),'CellRank'));
        cellNumber(i,t) = temp;
        t = t + 1;
        
        [temp t]
    end
end